import { Work_Sans } from "next/font/google";
import type { Metadata, Viewport } from "next";
import "@/app/scss/globals.scss";
import Header from "@/components/default/header/Header";
import { ApolloWrapper } from "@/lib/apollo-wrapper";
import { ToastProvider } from "@/contexts/toastContext";
import { AuthProvider } from "@/contexts/authContext";

export const metadata: Metadata = {
  title: "Fingers-App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  userScalable: false,
};

const workSans = Work_Sans({
  weight: ["100", "200", "300", "400", "500", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-Work_Sans",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={workSans.className}>
      <body>
        <ApolloWrapper>
          <ToastProvider>
            <AuthProvider>
              <Header />
              <main>{children}</main>
            </AuthProvider>
          </ToastProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
